# Generated by Django 5.1.2 on 2024-12-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='gender',
            new_name='sex',
        ),
    ]
