# Generated by Django 5.1.2 on 2024-12-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_payment_course_customers_delete_customercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
